
language: python

before_install:
  - sudo apt-get update
  - sudo apt-get -y install swig

install:
  - python setup.py install

script:
  - python setup.py test

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
